analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unnecessary_to_list_in_spreads: ignore
    invalid_use_of_protected_member: ignore
    prefer_final_locals: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    always_specify_types: false
