// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8YXtFI1dQOgeHCt5QJKT6HzO4V47V-4',
    appId: '1:579506953146:web:f09c357d305a488e955b83',
    messagingSenderId: '579506953146',
    projectId: 'propelex-1bc84',
    authDomain: 'propelex-1bc84.firebaseapp.com',
    storageBucket: 'propelex-1bc84.firebasestorage.app',
    measurementId: 'G-C69067WCV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmfGAoLRl-v6SLS8seif0QuTu8zwJN1ts',
    appId: '1:579506953146:android:a92aecbe240d7a49955b83',
    messagingSenderId: '579506953146',
    projectId: 'propelex-1bc84',
    storageBucket: 'propelex-1bc84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtV0HZEayB4LhvHlZuHsAeCql15cQZXIM',
    appId: '1:579506953146:ios:2fc80a50ecf350cf955b83',
    messagingSenderId: '579506953146',
    projectId: 'propelex-1bc84',
    storageBucket: 'propelex-1bc84.firebasestorage.app',
    iosClientId: '579506953146-sbf3ie594tih8v0hb4i4f5q6o4vh7seu.apps.googleusercontent.com',
    iosBundleId: 'com.newdawnstudio.propelex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtV0HZEayB4LhvHlZuHsAeCql15cQZXIM',
    appId: '1:579506953146:ios:0a417914df401332955b83',
    messagingSenderId: '579506953146',
    projectId: 'propelex-1bc84',
    storageBucket: 'propelex-1bc84.firebasestorage.app',
    iosClientId: '579506953146-0pigbn5vfr4i32k2up1t90ho02c0joo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.propelexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF8YXtFI1dQOgeHCt5QJKT6HzO4V47V-4',
    appId: '1:579506953146:web:553a2beac7715ca9955b83',
    messagingSenderId: '579506953146',
    projectId: 'propelex-1bc84',
    authDomain: 'propelex-1bc84.firebaseapp.com',
    storageBucket: 'propelex-1bc84.firebasestorage.app',
    measurementId: 'G-MZ7HHTTZ4W',
  );
}
